// =============================================================================
// Gemini API Utilities — Enhancement pass for Groq-generated content
// =============================================================================

import { GoogleGenerativeAI } from "@google/generative-ai";

const GEMINI_MODEL = "gemini-2.0-flash";

// ---------------------------------------------------------------------------
// Gemini API caller
// ---------------------------------------------------------------------------

export async function callGemini(prompt: string): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY environment variable is not set");
  }

  const genAI = new GoogleGenerativeAI(apiKey);
  const model = genAI.getGenerativeModel({ model: GEMINI_MODEL });

  const result = await model.generateContent(prompt);
  const response = result.response;
  return response.text();
}

// ---------------------------------------------------------------------------
// Enhancement prompt builder
// ---------------------------------------------------------------------------

export function buildEnhancementPrompt(
  groqContent: string,
  scrapedData: string,
  title: string
): string {
  return `You are an expert content enhancer for an Indian government jobs portal.

You are given:
1. An existing article (generated by another AI) about "${title}"
2. The raw scraped data from the official source page

Your job is to IMPROVE the existing article by filling in any missing or incomplete information using the raw scraped data. Specifically:

WHAT TO ADD/FIX:
- Vacancy breakdown tables (Post Name | Pay Level | Vacancies) if missing or incomplete
- Salary/pay scale tables if the data exists in the scraped text but is missing from the article
- Application fee tables (Category | Amount) with all category rows from the data
- Exam pattern tables (Section | Questions | Marks | Duration) if data is available
- Important dates that exist in the scraped data but were missed
- Age limit details and category-wise relaxations
- Any other factual details present in the scraped data but absent from the article

RULES:
- Do NOT invent or fabricate any information — only use what's in the scraped data
- Keep the same markdown structure (## headings) and conversational, mentor-like tone
- Keep the same section order as the original article
- Do NOT add a top-level # heading — the page already has one
- Use Hindi-English terms naturally (lakh, crore, sarkari naukri, bharti, etc.) where appropriate
- If the original article already covers something well, keep it as-is
- Use markdown tables for structured data (vacancies, fees, exam pattern, dates, salary)
- Do NOT wrap the output in any code fences — return plain markdown only
- Do NOT include any JSON blocks — return only the article markdown
- Maintain at least the same word count as the original — do not shorten the article

BANNED PHRASES — never write any of these:
- 'certain date'
- 'will be announced'
- 'may vary'
- 'to be announced'
- 'TBA'
If a date or detail is unknown, write 'Not yet released' or omit the row entirely.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXISTING ARTICLE:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${groqContent}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RAW SCRAPED DATA:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${scrapedData}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Now return the full improved article in markdown. Output ONLY the article — no explanations, no JSON, no code fences around the entire response.`;
}

// ---------------------------------------------------------------------------
// Scheme Enhancement prompt builder
// ---------------------------------------------------------------------------

export function buildSchemeEnhancementPrompt(
  groqContent: string,
  scrapedData: string,
  title: string
): string {
  return `You are an expert content enhancer for an Indian government schemes portal.

You are given:
1. An existing article (generated by another AI) about "${title}"
2. The raw scraped data from the official source page

Your job is to IMPROVE the existing article by filling in any missing or incomplete information using the raw scraped data. Specifically:

WHAT TO ADD/FIX:
- Missing eligibility criteria details
- Missing benefits and financial assistance amounts
- Missing required documents
- Missing application process steps
- Important dates or deadlines from the scraped data
- Official portal links and helpline numbers
- Any other factual details present in the scraped data but absent from the article

RULES:
- Do NOT invent or fabricate any information — only use what's in the scraped data
- Keep the same markdown structure (## headings) and helpful, conversational tone
- Keep the same section order as the original article
- Do NOT add a top-level # heading — the page already has one
- Use Hindi-English terms naturally (sarkari yojana, labh, patra, etc.) where appropriate
- If the original article already covers something well, keep it as-is
- Do NOT wrap the output in any code fences — return plain markdown only
- Do NOT include any JSON blocks — return only the article markdown
- Maintain at least the same word count as the original — do not shorten the article

BANNED PHRASES — never write any of these:
- 'certain date'
- 'will be announced'
- 'may vary'
- 'to be announced'
- 'TBA'
If a detail is unknown, write 'Not yet available' or omit the section entirely.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXISTING ARTICLE:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${groqContent}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RAW SCRAPED DATA:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${scrapedData}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Now return the full improved article in markdown. Output ONLY the article — no explanations, no JSON, no code fences around the entire response.`;
}

// ---------------------------------------------------------------------------
// Entrance Exam Enhancement prompt builder
// ---------------------------------------------------------------------------

export function buildExamEnhancementPrompt(
  groqContent: string,
  scrapedData: string,
  title: string
): string {
  return `You are an expert content enhancer for an Indian entrance exam portal.

You are given:
1. An existing article (generated by another AI) about "${title}"
2. The raw scraped data from the official source page

Your job is to IMPROVE the existing article by filling in any missing or incomplete information using the raw scraped data. Specifically:

WHAT TO ADD/FIX:
- Exam pattern tables (Section | Questions | Marks | Duration) if missing or incomplete
- Syllabus details if available in the scraped data
- Important dates (application start/end, exam date, admit card, result)
- Eligibility criteria details
- Application fee tables (Category | Amount) with all category rows
- Admit card and result download information
- Any other factual details present in the scraped data but absent from the article

IMPORTANT:
- NEVER mention salary, pay scale, or compensation — entrance exams have none
- Do NOT add a Salary & Benefits section

RULES:
- Do NOT invent or fabricate any information — only use what's in the scraped data
- Keep the same markdown structure (## headings) and mentor-like tone
- Keep the same section order as the original article
- Do NOT add a top-level # heading — the page already has one
- Write in a helpful tone for Indian students and exam aspirants
- If the original article already covers something well, keep it as-is
- Use markdown tables for structured data (exam pattern, fees, dates)
- Do NOT wrap the output in any code fences — return plain markdown only
- Do NOT include any JSON blocks — return only the article markdown
- Maintain at least the same word count as the original — do not shorten the article

BANNED PHRASES — never write any of these:
- 'certain date'
- 'will be announced'
- 'may vary'
- 'to be announced'
- 'TBA'
If a date or detail is unknown, write 'Not yet released' or omit the row entirely.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXISTING ARTICLE:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${groqContent}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RAW SCRAPED DATA:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${scrapedData}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Now return the full improved article in markdown. Output ONLY the article — no explanations, no JSON, no code fences around the entire response.`;
}
