// GENERATED by scripts/generate-redirected-slugs.mjs. Do not edit by hand.
//
// Blog slugs that next.config.js redirects away. Nothing on the site should
// link to these: the link would cost a redirect hop for both crawlers and
// readers. Re-run the generator after changing the redirect table.

export const REDIRECTED_BLOG_SLUGS: ReadonlySet<string> = new Set([
  "ayushman-bharat-card-2026-apply-download-use",
  "best-government-jobs-for-women-in-india-2026-career-guide",
  "complete-guide-to-pm-kisan-yojana",
  "ctet-2026-eligibility-exam-pattern-syllabus-preparation-guide",
  "government-jobs-after-12th-in-india-2026",
  "how-to-apply-for-ibps-po-2026",
  "how-to-apply-for-ssc-cgl-2026",
  "how-to-apply-pm-mudra-loan-2026-step-by-step-guide",
  "how-to-clear-ibps-clerk-2026-first-attempt",
  "how-to-download-ibps-po-admit-card-2026",
  "how-to-prepare-for-ssc-cgl",
  "ibps-po-2026-preparation-guide",
  "ibps-po-vs-sbi-po-2026-comparison",
  "pm-kisan-samman-nidhi-2026-status-check",
  "pm-kisan-samman-nidhi-apply-check-status-fix-errors",
  "railway-group-d-2026-notification-dates-apply-online",
  "rn-ntpc-2026-posts-eligibility-exam-pattern-preparation-guide",
  "rrb-ntpc-2026-posts-eligibility-exam-pattern-preparation-guide",
  "sbi-po-2026-preparation-guide",
  "ssc-cgl-syllabus-2026-complete-topic-wise-breakdown",
  "ssc-cgl-tier-2-score-card-2026-how-to-check-marks",
  "ssc-chsl-2026-admit-card-download-hall-ticket",
  "top-10-govt-jobs-after-12th-2026",
  "upsc-cse-2026-notification-dates-eligibility-apply-online",
  "upsc-eligibility-2026-age-limit-qualification-attempts",
  "upsc-mains-2026-preparation-strategy-8-week-plan",
  "upsc-mains-2026-preparation-strategy-9-week-plan",
  "upsc-prelims-result-2026-cutoff-paper-analysis",
  "wb-gram-panchayat-recruitment-2026-complete-guide",
]);

export function isRedirectedBlogSlug(slug: string): boolean {
  return REDIRECTED_BLOG_SLUGS.has(slug);
}
